behaviors:
  Driver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 1.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.8
        demo_path: Demos/RacingTrack_0.demo
    behavioral_cloning:
      strength: 1.0
      demo_path: Demos/RacingTrack_0.demo
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 10000
